### ISSUE TITLE
预览video时点击编辑崩溃

### ISSUE THREAD

**Issue by lknlll** [guoxiaoxing/phoenix#10]
java.lang.IllegalStateException: BitmapFactory.decodeFile(filePath, options) must not be null
	at com.guoxiaoxing.phoenix.picker.util.PictureUtils.getImageBitmap(PictureUtils.kt:46)
	at com.guoxiaoxing.phoenix.picker.ui.editor.PictureEditFragment.setupData(PictureEditFragment.kt:191)
	at com.guoxiaoxing.phoenix.picker.ui.editor.PictureEditFragment.onViewCreated(PictureEditFragment.kt:119)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1430)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
	at android.os.Handler.handleCallback(Handler.java:761)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6577)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by lknlll** [comment]
是不是可以在预览视频时将编辑隐去

**Comment by guoxiaoxing** [comment]
感谢反馈，新版已修复。[![Download](https://api.bintray.com/packages/guoxiaoxing/maven/phoenix/images/download.svg)](https://bintray.com/guoxiaoxing/maven/phoenix/_latestVersion)

**Comment by lknlll** [comment]
感谢大神~

**Comment by guoxiaoxing** [comment]
T_T小菜鸟一只，勤奋学习ing...
