### ISSUE TITLE
拒绝写入权限崩溃小米5splus

### ISSUE THREAD

**Issue by heartyo** [guoxiaoxing/phoenix#15]
java.lang.RuntimeException: Unable to destroy activity {com.guoxiaoxing.phoenix.demo/com.guoxiaoxing.phoenix.picker.ui.picker.PickerActivity}: kotlin.UninitializedPropertyAccessException: lateinit property animation has not been initialized
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4271)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4289)
	at android.app.ActivityThread.-wrap6(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6321)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property animation has not been initialized
	at com.guoxiaoxing.phoenix.picker.ui.picker.PickerActivity.onDestroy(PickerActivity.kt:407)
	at android.app.Activity.performDestroy(Activity.java:7058)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4258)
	... 9 more

**Comment by guoxiaoxing** [comment]
新版已修复1.0.10
