### ISSUE TITLE
HuaweiMate9 横屏拍照闪退

### ISSUE THREAD

**Issue by merhong2012** [guoxiaoxing/phoenix#64]
1.0.11横屏拍照闪退
1.0.15 竖屏横屏拍照闪退
安卓8.0

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
        at com.guoxiaoxing.phoenix.picker.ui.camera.manager.impl.Camera2Manager.openCamera(Camera2Manager.java:191)
        at com.guoxiaoxing.phoenix.picker.ui.camera.manager.impl.Camera2Manager.openCamera(Camera2Manager.java:61)
        at com.guoxiaoxing.phoenix.picker.ui.camera.lifecycle.impl.Camera2Lifecycle.onCameraClosed(Camera2Lifecycle.java:177)
        at com.guoxiaoxing.phoenix.picker.ui.camera.lifecycle.impl.Camera2Lifecycle.onCameraClosed(Camera2Lifecycle.java:36)
        at com.guoxiaoxing.phoenix.picker.ui.camera.manager.impl.Camera2Manager$4$1.run(Camera2Manager.java:234)
```

**Comment by merhong2012** [comment]
补充错误信息
```
08 14:55:05.485 23715-23715/net.ppsz.paopao E/Camera2Manager: Error setting flash: 
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.camera2.CaptureRequest$Builder.set(android.hardware.camera2.CaptureRequest$Key, java.lang.Object)' on a null object reference
        at com.guoxiaoxing.phoenix.picker.ui.camera.manager.impl.Camera2Manager.setFlashModeAndBuildPreviewRequest(Camera2Manager.java:707)
        at com.guoxiaoxing.phoenix.picker.ui.camera.manager.impl.Camera2Manager.setFlashMode(Camera2Manager.java:244)
        at com.guoxiaoxing.phoenix.picker.ui.camera.lifecycle.impl.Camera2Lifecycle.setFlashMode(Camera2Lifecycle.java:133)
        at com.guoxiaoxing.phoenix.picker.ui.camera.CameraFragment.onFlashModeChanged(CameraFragment.java:521)
        at com.guoxiaoxing.phoenix.picker.ui.camera.CameraFragment.notifyListeners(CameraFragment.java:283)
        at com.guoxiaoxing.phoenix.picker.ui.camera.CameraFragment.onViewCreated(CameraFragment.java:279)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1439)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
```
