### ISSUE TITLE
部分4.4.4和4.4.2系统的机型报错

### ISSUE THREAD

**Issue by Guangdinghou** [guoxiaoxing/phoenix#65]
哈喽，部分4.4.4和4.4.2系统的机型上 报如下错误：
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sinosig.ygqd/com.guoxiaoxing.phoenix.picker.ui.picker.PickerActivity}: kotlin.TypeCastException: null cannot be cast to non-null type android.view.ViewGroup
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2464)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2526)
	at android.app.ActivityThread.access$800(ActivityThread.java:174)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:229)
	at android.app.ActivityThread.main(ActivityThread.java:5493)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: kotlin.TypeCastException: null cannot be cast to non-null type android.view.ViewGroup
	at com.guoxiaoxing.phoenix.picker.util.ToolbarUtil.setRootView(ToolbarUtil.kt:38)
	at com.guoxiaoxing.phoenix.picker.util.ToolbarUtil.setColor(ToolbarUtil.kt:30)
	at com.guoxiaoxing.phoenix.picker.util.ToolbarUtil.setColorNoTranslucent(ToolbarUtil.kt:85)
	at com.guoxiaoxing.phoenix.picker.ui.picker.PickerActivity.onCreate(PickerActivity.kt:93)
	at android.app.Activity.performCreate(Activity.java:5463)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
	at cn.jiguang.a.a.c.a.a.d.callActivityOnCreate(Unknown Source)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2418)
	... 11 more
kotlin.TypeCastException: null cannot be cast to non-null type android.view.ViewGroup
	at com.guoxiaoxing.phoenix.picker.util.ToolbarUtil.setRootView(ToolbarUtil.kt:38)
	at com.guoxiaoxing.phoenix.picker.util.ToolbarUtil.setColor(ToolbarUtil.kt:30)
	at com.guoxiaoxing.phoenix.picker.util.ToolbarUtil.setColorNoTranslucent(ToolbarUtil.kt:85)
	at com.guoxiaoxing.phoenix.picker.ui.picker.PickerActivity.onCreate(PickerActivity.kt:93)
	at android.app.Activity.performCreate(Activity.java:5463)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
	at cn.jiguang.a.a.c.a.a.d.callActivityOnCreate(Unknown Source)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2418)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2526)
	at android.app.ActivityThread.access$800(ActivityThread.java:174)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:229)
	at android.app.ActivityThread.main(ActivityThread.java:5493)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by cuipengxiang** [comment]
是的，我在4.4.4也遇到这个问题

**Comment by Sz-song** [comment]
vivo x5v android版本4.4.4 遇见这个相同的问题

**Comment by Guangdinghou** [comment]
> vivo x5v android版本4.4.4 遇见这个相同的问题，请问有解决方案吗？
我换成最新版，没崩溃。。

**Comment by Sz-song** [comment]
> > vivo x5v android版本4.4.4 遇见这个相同的问题，请问有解决方案吗？
> > 我换成最新版，没崩溃。。

我用的是1.0.15最新版本啊

**Comment by Guangdinghou** [comment]
啊哈哈 那就分析下代码吧~


| |
guangdinghou
|
|
guangdinghou@yeah.net
|
签名由网易邮箱大师定制
在2019年4月8日 11:41，Sz-song<notifications@github.com> 写道：

vivo x5v android版本4.4.4 遇见这个相同的问题，请问有解决方案吗？
我换成最新版，没崩溃。。

我用的是1.0.15最新版本啊
