### ISSUE TITLE
编辑图片的时候报错了

### ISSUE THREAD

**Issue by gaha110** [guoxiaoxing/phoenix#70]
java.lang.IllegalStateException: tv_check must not be null
                                                       at com.guoxiaoxing.phoenix.picker.ui.picker.PreviewFragment.isPreviewEggs(PreviewFragment.kt:204)
                                                       at com.guoxiaoxing.phoenix.picker.ui.picker.PreviewFragment.access$isPreviewEggs(PreviewFragment.kt:38)
                                                       at com.guoxiaoxing.phoenix.picker.ui.picker.PreviewFragment$setupData$1.onPageScrolled(PreviewFragment.kt:169)
                                                       at android.support.v4.view.ViewPager.dispatchOnPageScrolled(ViewPager.java:1924)
                                                       at android.support.v4.view.ViewPager.onPageScrolled(ViewPager.java:1898)
                                                       at android.support.v4.view.ViewPager.pageScrolled(ViewPager.java:1836)
                                                       at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:688)
                                                       at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:664)
                                                       at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:625)
                                                       at android.support.v4.view.ViewPager.dataSetChanged(ViewPager.java:1080)
                                                       at android.support.v4.view.ViewPager$PagerObserver.onChanged(ViewPager.java:3091)
                                                       at android.support.v4.view.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:290)
                                                       at com.guoxiaoxing.phoenix.picker.ui.picker.PreviewFragment.onActivityResult(PreviewFragment.kt:438)
                                                       at com.guoxiaoxing.phoenix.picker.ui.editor.PictureEditFragment.finish(PictureEditFragment.kt:271)
                                                       at com.guoxiaoxing.phoenix.picker.ui.editor.PictureEditFragment.access$finish(PictureEditFragment.kt:57)
                                                       at com.guoxiaoxing.phoenix.picker.ui.editor.PictureEditFragment$ImageComposeTask.onPostExecute(PictureEditFragment.kt:598)
                                                       at com.guoxiaoxing.phoenix.picker.ui.editor.PictureEditFragment$ImageComposeTask.onPostExecute(PictureEditFragment.kt:543)
                                                       at android.os.AsyncTask.finish(AsyncTask.java:695)
                                                       at android.os.AsyncTask.-wrap1(Unknown Source:0)
                                                       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
                                                       at android.os.Handler.dispatchMessage(Handler.java:106)
                                                       at android.os.Looper.loop(Looper.java:171)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6633)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by ccaong** [comment]
同样的问题，如果不选择，直接编辑，就会有这个错误
