### ISSUE TITLE
压缩视频时候报错

### ISSUE THREAD

**Issue by duanhai123** [guoxiaoxing/phoenix#76]
压缩视频时候报错Fatal error while transcoding, this might be invalid format or bug in engine or Android.这个是什么原因用的是同步的方法

**Comment by guoxiaoxing** [comment]
视频格式的问题

**Comment by CherryLover** [comment]
我使用 Android 原相机录制了一个视频，然后通过视频压缩库进行压缩，直接就提示
```log
Fatal error while transcoding, this might be invalid format or bug in engine or Android.
    com.guoxiaoxing.phoenix.compress.video.engine.InvalidOutputFormatException: Non-baseline AVC video profile is not supported by Android OS, actual profile_idc: 100
        at com.guoxiaoxing.phoenix.compress.video.engine.MediaFormatValidator.validateVideoOutputFormat(MediaFormatValidator.java:25)
        at com.guoxiaoxing.phoenix.compress.video.engine.MediaTranscoderEngine$1.onDetermineOutputFormat(MediaTranscoderEngine.java:147)
        at com.guoxiaoxing.phoenix.compress.video.engine.QueuedMuxer.onSetOutputFormat(QueuedMuxer.java:51)
        at com.guoxiaoxing.phoenix.compress.video.engine.QueuedMuxer.setOutputFormat(QueuedMuxer.java:46)
        at com.guoxiaoxing.phoenix.compress.video.engine.VideoTrackTranscoder.drainEncoder(VideoTrackTranscoder.java:192)
        at com.guoxiaoxing.phoenix.compress.video.engine.VideoTrackTranscoder.stepPipeline(VideoTrackTranscoder.java:90)
        at com.guoxiaoxing.phoenix.compress.video.engine.MediaTranscoderEngine.runPipelines(MediaTranscoderEngine.java:176)
        at com.guoxiaoxing.phoenix.compress.video.engine.MediaTranscoderEngine.transcodeVideo(MediaTranscoderEngine.java:82)
        at com.guoxiaoxing.phoenix.compress.video.VideoCompressor.syncTranscodeVideo(VideoCompressor.java:81)
```
