### ISSUE TITLE
Android 7.0 拍照崩溃

### ISSUE THREAD

**Issue by HYVincent** [guoxiaoxing/phoenix#9]
11-26 16:20:53.273 4992-4992/com.guoxiaoxing.phoenix.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.guoxiaoxing.phoenix.demo, PID: 4992
                                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{com.guoxiaoxing.phoenix.demo/com.guoxiaoxing.phoenix.picker.ui.camera.CameraActivity}: java.lang.IllegalStateException: intent.getParcelableExtr…xConstant.PHOENIX_OPTION) must not be null
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
                                                                                at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                at android.os.Looper.loop(Looper.java:156)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                                                                             Caused by: java.lang.IllegalStateException: intent.getParcelableExtr…xConstant.PHOENIX_OPTION) must not be null
                                                                                at com.guoxiaoxing.phoenix.picker.ui.BaseActivity.onCreate(BaseActivity.kt:63)
                                                                                at com.guoxiaoxing.phoenix.picker.ui.camera.CameraActivity.onCreate(CameraActivity.kt:20)
                                                                                at android.app.Activity.performCreate(Activity.java:6910)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864) 
                                                                                at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                at android.os.Looper.loop(Looper.java:156) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6523) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by guoxiaoxing** [comment]
[![Download](https://api.bintray.com/packages/guoxiaoxing/maven/phoenix/images/download.svg)](https://bintray.com/guoxiaoxing/maven/phoenix/_latestVersion)

新版已修复
